version: '3.9'

services:
  postgres-compose:
    image: postgres:alpine
    container_name: postgres-tech-radar
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5433:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin-tech-radar
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "4240:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  dev-db-data: