spring:
  profiles:
    active: local
#    active: docker

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: tech-news

server:
  error:
    include-stacktrace: never

  port: 0

upload:
  dir: ${user.dir}/newsUpload