spring:
  profiles:
    active: local
#    active: docker

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: tech-news

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

server:
  error:
    include-stacktrace: never

  port: 0

upload:
  dir: ${user.dir}/newsUpload

populate:
  url: ${BASE_URL}

frontend:
  host: http://127.0.0.1:3000

