version: '3.9'
services:
  service-discovery:
    container_name: service-discovery
    build:
      context: ./service-discovery
    ports:
      - 8765:8765
    volumes:
      - service-discovery-volume
    networks:
      - bdtc-net

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    environment:
      - EUREKA_URL=http://service-discovery:8765/eureka
    ports:
      - 8766:8766
    volumes:
      - api-gateway-volume
    networks:
      - bdtc-net


volumes:
  service-discovery-volume:

  api-gateway-volume:


networks:
  bdtc-net:
    driver: bridge