server:
  port: 8766

spring:
  profiles:
    active: local
#    active: docker

  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

          lower-case-service-id: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS