version: '3.3'
services:
  service-discovery:
    container_name: service-discovery
    build:
      context: ../service-discovery
    ports:
      - "0.0.0.0:8765:8765"
    networks:
      - bdtc-net

  api-gateway:
    depends_on:
      - service-discovery
    container_name: api-gateway
    build:
      context: ../api-gateway
    environment:
      - EUREKA_URL=http://service-discovery:8765/eureka
    ports:
      - "0.0.0.0:8766:8766"
    networks:
      - bdtc-net

  image-service:
    depends_on:
      - api-gateway
    container_name: image-service
    build:
      context: ../image-service
    env_file:
      - ../image-service/.env
    volumes:
      - uploads-volume:/app/uploads
    networks:
      - bdtc-net

  tech-news:
    depends_on:
      - image-service
    container_name: tech-news
    build:
      context: ../tech-news
    env_file:
      - ../tech-news/.env
    environment:
      - DATABASE_URL=jdbc:postgresql://tech-news-db:5432/tech_news
      - EUREKA_URL=http://service-discovery:8765/eureka
      - GATEWAY_URL=http://10.234.90.77:8766/tech-news
    networks:
      - bdtc-net

  tech-news-db:
    image: postgres
    container_name: tech-news-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: tech_news
    ports:
      - 6968:5432
    volumes:
      - tech-news-db-volume:/var/lib/postgresql/data/
    networks:
      - bdtc-net

  tech-radar:
    depends_on:
      - api-gateway
      - tech-radar-db
    container_name: tech-radar
    build:
      context: ../tech-radar
    env_file:
      - ../tech-radar/.env
    environment:
      - DATABASE_URL=jdbc:postgresql://tech-radar-db:5432/tech_radar
      - EUREKA_URL=http://service-discovery:8765/eureka
    networks:
      - bdtc-net

  tech-radar-db:
    image: postgres
    container_name: tech-radar-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: tech_radar
    ports:
      - 6967:5432
    volumes:
      - tech-radar-db-volume:/var/lib/postgresql/data/
    networks:
      - bdtc-net

volumes:
  uploads-volume:

  tech-news-db-volume:

  tech-radar-db-volume:

networks:
  bdtc-net:
    driver: bridge