spring:
  profiles:
    active: local
#    active: docker

  application:
    name: tech-radar

  jpa:
    hibernate:
      ddl-auto: update
    jdbc:
      error_handling:
        throw_sql_exceptions: true
server:
  error:
    include-stacktrace: never

  port: 4241
#  port: 0

#frontend:
#  host: http://127.0.0.1:3000