spring:
  profiles:
    active: local

  application:
    name: tech-radar

  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never

  port: 4241

#frontend:
#  host: http://127.0.0.1:3000